Repository FRONTENDBOOTCAMP-13th/next-to-euid, pull requests merged in 2025-03, with the labels that each got.

#5 Feat/component start
  README.md
  component-start.html
  index.html
  src/main.js
  src/style.css
  src/styles/component-start.css
  src/theme.css
  theme.html
Labels: documentation

#6 Feat/component start
  package-lock.json
  package.json
  public/common/a11y.css
  public/common/mini-reset.css
  src/component-start.html
  src/style.css
  src/styles/component-start.css
  src/theme.css
Labels: bug

#7 github bug fixed
  package-lock.json
  package.json
Labels: bug

#8 Feat/component start
  component-start.html
  index.html
  src/asset/favicon/tripple-oil.svg
  src/asset/icon/start-chat.svg
  src/asset/icon/start-common-check.svg
  src/asset/icon/start-common-logo-EUID.svg
  src/asset/icon/start-common-plus.svg
  src/asset/icon/start-common-position.svg
  src/asset/icon/start-common-search.svg
  src/asset/icon/start-down.svg
  src/asset/icon/start-fullChat.svg
  src/asset/icon/start-fullFile.svg
  src/asset/icon/start-fullHome.svg
  src/asset/icon/start-fullMy.svg
  src/asset/icon/start-fullmap.svg
  src/asset/icon/start-home.svg
  src/asset/icon/start-left.svg
  src/asset/icon/start-life.svg
  src/asset/icon/start-map.svg
  src/asset/icon/start-my.svg
  src/asset/icon/start-right.svg
  src/asset/icon/start-up.svg
  src/component-start.html
  src/style.css
  src/styles/component-start.css
Labels: enhancement

#9 Feat/Added component board page-1 card component
  src/asset/icon/board-calender14x14-light.svg
  src/asset/icon/board-calender20x20-dark.svg
  src/asset/icon/board-fullpeople14x14-light.svg
  src/asset/icon/board-fullpeople20x20-dark.svg
  src/asset/icon/board-people14x14-dark.svg
  src/asset/icon/board-people14x14-light.svg
  src/asset/icon/board-people20x20-dark.svg
  src/asset/icon/boardContent-organizer20x20.svg
  src/asset/icon/chatScreen-send20x20.svg
  src/asset/icon/chatScreen-smile20x20.svg
  src/asset/icon/withWho-sex20x20.svg
  src/asset/icon/writeActivities-minus20x20.svg
  src/asset/icon/writeActivities-time18x18.svg
  src/component-border copy.html
  src/component-border.html
  src/styles/component-border copy.css
  src/styles/component-border.css
  src/theme.css
Labels: enhancement

#10 Feat/component main
  src/asset/alramBell.svg
  src/asset/direction.svg
  src/asset/down.svg
  src/asset/hamburger.svg
  src/asset/heart.svg
  src/asset/home.svg
  src/asset/more.svg
  src/asset/plus.svg
  src/asset/search.svg
  src/asset/share.svg
  src/asset/🎈.svg
  src/component-main.html
  src/styles/component-main.css
Labels: enhancement

#12 🍄 Feat/component border - Refactored class names, updated board components
  src/component-board.html
  src/component-border copy.html
  src/styles/component-board.css
  src/styles/component-border copy.css
Labels: enhancement

#11 feat🍄 : Add start section components
  component-start.html
  src/styles/component-start.css
Labels: enhancement

#13 Feat/component profile
  README.md
  component-profile.html
  index.html
  src/asset/icon/profile-Q&A.svg
  src/asset/icon/profile-alramBell.svg
  src/asset/icon/profile-close.svg
  src/asset/icon/profile-detailCard.svg
  src/asset/icon/profile-heart.svg
  src/asset/icon/profile-information.svg
  src/asset/icon/profile-more.svg
  src/asset/icon/profile-password.svg
  src/asset/icon/profile-pencil.svg
  src/asset/icon/profile-people.svg
  src/asset/icon/profile-speech.svg
  src/asset/icon/profile.svg
  src/styles/component-profile.css
Labels: enhancement

#16 Feat/component main
  src/asset/icon/main-alramBell.svg
  src/asset/icon/main-direction.svg
  src/asset/icon/main-down.svg
  src/asset/icon/main-hamburger.svg
  src/asset/icon/main-heart.svg
  src/asset/icon/main-home.svg
  src/asset/icon/main-more.svg
  src/asset/icon/main-plus.svg
  src/asset/icon/main-search.svg
  src/asset/icon/main-share.svg
  src/component-main.html
  src/styles/component-main.css
Labels: enhancement

#17 refactor♻️: Revised title
  src/component-main.html
Labels: refactor

#18 Feat/component profile
  component-profile.html
  index.html
  src/asset/alramBell.svg
  src/asset/direction.svg
  src/asset/down.svg
  src/asset/hamburger.svg
  src/asset/heart.svg
  src/asset/home.svg
  src/asset/more.svg
  src/asset/plus.svg
  src/asset/search.svg
  src/asset/share.svg
  src/asset/🎈.svg
  src/component-board.html
  src/component-main.html
  src/component-profile.html
  src/component-start.html
  src/styles/component-main.css
  src/styles/component-profile.css
  theme.html
Labels: enhancement

#21 feat🍄 : Add dev status board (1차 레이아웃)
  index.html
  src/asset/icon/redmush-logo.svg
  src/style.css
Labels: enhancement

#22 Feat/status board
  .prettierrc.cjs
  src/component-board.html
  src/component-main.html
  src/style.css
  src/styles/component-board.css
  src/styles/component-main.css
  src/styles/component-profile.css
  src/styles/component-start.css
  src/theme.css
Labels: refactor

#24 Feat/page-main
  .prettierrc.cjs
  src/component-main.html
  src/page-main.html
  src/styles/page-main.css
Labels: enhancement

#25 Feat/login page
  src/component-board.html
  src/component-profile.html
  src/component-start.html
  src/login-welcome.html
  src/login.html
  src/style.css
  src/styles/login-welcome.css
  src/styles/login.css
Labels: refactor

#23 Feat/start forgot pw
  src/page-start-forgot-pw.html
  src/styles/page-start-forgot-pw.css
Labels: refactor

#28 feat🍄 : Added login interface
  src/login-welcome.html
  src/pages/login-welcome.html
  src/styles/login-welcome.css
Labels: enhancement

#29 Feat/start forgot pw
  index.html
  src/js/page-start-forgot-pw.js
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw-number.css
  src/styles/page-start-forgot-pw.css
Labels: enhancement

#30 refactor♻️: Modify files by .prettierrc.cjs
  src/login-welcome.html
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw.css
Labels: refactor

#32 feat🍄 : Add forgot-pw HTML
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/styles/page-start-forgot-pw-number.css
  src/styles/page-start-forgot-pw.css
Labels: enhancement

#37 feat🍄 : Improve a11y, update welcome modal
  src/login-welcome.html
  src/login-welcome.js
  src/login.html
  src/login.js
  src/signup.html
  src/signup.js
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/signup.css
Labels: enhancement

#39 refactor♻️: move js files to src/js folder
  src/js/login-welcome.js
  src/js/login.js
  src/js/main.js
  src/js/signup.js
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/signup.css
Labels: refactor

#42 chore ⚙️: Move js files to src/js folder
  src/main.js
Labels: refactor

#41 Feat/page boardstudy
  src/js/login.js
  src/page-board-study-search.html
  src/page-board-study-write.html
  src/styles/page-board-study-search.css
  src/styles/page-board-study-write.css
Labels: enhancement

#45 chore ⚙️: Changed path of js files
  src/login-welcome.html
  src/login.html
  src/pages/login-welcome.html
  src/signup.html
  vite.config.js
Labels: refactor

#47 feat🍄 : Applied grid
  src/login.html
  src/page-main.html
  src/styles/login copy.css
  src/styles/login.css
  src/styles/page-main.css
Labels: refactor

#48 4차 배포 (Grid 적용)
  src/login.html
  src/page-main.html
  src/styles/login copy.css
  src/styles/login.css
  src/styles/page-main.css
Labels: refactor

#49 refactor♻️: Fixed layout for login and signup page
  src/styles/login copy.css
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/signup.css
Labels: refactor

#52 Feat/page login-welcome 수정
  src/js/login-welcome.js
  src/js/login.js
  src/js/page-start-forgot-pw.js
  src/js/signup.js
  src/login-welcome.html
  src/login.html
  src/main.js
  src/page-board-study-search.html
  src/page-board-study-write.html
  src/signup.html
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/page-board-study-search.css
  src/styles/page-main.css
  src/styles/signup.css
Labels: refactor

#53 6차 배포 (웰컴 페이지 레이아웃, 말풍선 수정)
  src/js/login-welcome.js
  src/js/login.js
  src/js/page-start-forgot-pw.js
  src/js/signup.js
  src/login-welcome.html
  src/login.html
  src/main.js
  src/page-board-study-search.html
  src/page-board-study-write.html
  src/signup.html
  src/styles/login-welcome.css
  src/styles/login.css
  src/styles/page-board-study-search.css
  src/styles/page-main.css
  src/styles/signup.css
Labels: refactor

#54 refactor♻️: Semi-Final Complete page-main
  src/asset/img/page-main-김진우.jpg
  src/asset/img/page-main-박치열.jpg
  src/asset/img/page-main-염진희.jpg
  src/asset/img/page-main-최혜수.jpg
  src/page-boardwith.html
  src/page-main.html
  src/styles/page-main.css
Labels: refactor

#55 7차 배포( main 페이지 코드 리팩토링)
  src/asset/img/page-main-김진우.jpg
  src/asset/img/page-main-박치열.jpg
  src/asset/img/page-main-염진희.jpg
  src/asset/img/page-main-최혜수.jpg
  src/page-boardwith.html
  src/page-main.html
  src/styles/page-main.css
Labels: refactor

#56 Feat/login page
  src/js/login.js
  src/login.html
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/styles/login.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw-number.css
  src/styles/page-start-forgot-pw.css
Labels: documentation, enhancement

#57 feat🍄 : Modify index design, layout
  index.html
  src/asset/icon/redmush-logo.svg
  src/asset/img/euid-og.png
  src/asset/img/index-bg.png
  src/asset/img/tripple-oil-og.jpeg
  src/main.js
  src/style.css
Labels: enhancement, refactor

#58 Feat/index-html prettier 문법검사, 레이아웃 수정
  src/main.js
  src/style.css
Labels: refactor

#59 8차 배포
  index.html
  src/asset/icon/redmush-logo.svg
  src/asset/img/euid-og.png
  src/asset/img/index-bg.png
  src/asset/img/tripple-oil-og.jpeg
  src/js/login.js
  src/login.html
  src/main.js
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/style.css
  src/styles/login.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw-number.css
  src/styles/page-start-forgot-pw.css
Labels: enhancement, refactor

#60 Feat/page boardwith
  src/component-board.html
  src/component-main.html
  src/component-profile.html
  src/component-start.html
  src/login-welcome.html
  src/login.html
  src/page-main.html
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
Labels: refactor

#61 9차 배포
  src/component-board.html
  src/component-main.html
  src/component-profile.html
  src/component-start.html
  src/login-welcome.html
  src/login.html
  src/page-main.html
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
Labels: refactor

#62 Feat/html validator syntax error fixed
  index.html
  src/component-board.html
  src/component-main.html
  src/component-profile.html
  src/component-start.html
  src/js/login.js
  src/login-welcome.html
  src/login.html
  src/page-board-study-search.html
  src/page-board-study-write.html
  src/page-boardwith.html
  src/page-main.html
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/signup.html
  src/styles/login.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw.css
Labels: bug, refactor

#63 Feat/login page
  README.md
  index.html
  src/style.css
Labels: enhancement

#64 추가 배포
  README.md
  index.html
  src/component-board.html
  src/component-main.html
  src/component-profile.html
  src/component-start.html
  src/js/login.js
  src/login-welcome.html
  src/login.html
  src/page-board-study-search.html
  src/page-board-study-write.html
  src/page-boardwith.html
  src/page-main.html
  src/page-start-forgot-pw-email.html
  src/page-start-forgot-pw-number.html
  src/page-start-forgot-pw.html
  src/signup.html
  src/style.css
  src/styles/login.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw.css
Labels: enhancement

#65 fix🐛: Fix bug in *-pw-email.html
  src/page-start-forgot-pw-email.html
Labels: bug

#66 docs📝: Update README.md
  README.md
Labels: documentation

#67 [Ally] Fixed HTML structure errors, improved a11y and contrast, and confirmed login ID tag change during dev→qna merge.
  index.html
  src/login.html
  src/page-main.html
  src/signup.html
  src/style.css
  src/styles/login-welcome.css
  src/theme.css
Labels: refactor

#68 [Ally] Improved accessibility through semantic markup, better screen reader support, and reduced redundancy based on WAVE evaluation.
  src/login-welcome.html
  src/login.html
  src/page-main.html
  src/page-start-forgot-pw-email.html
  src/signup.html
  src/style.css
  src/styles/login-welcome.css
  src/styles/login.css
  src/theme.css
Labels: refactor

#69 최종 배포
  README.md
  index.html
  src/login-welcome.html
  src/login.html
  src/page-start-forgot-pw-email.html
  src/signup.html
  src/style.css
  src/styles/login-welcome.css
  src/styles/login.css
  src/theme.css
Labels: refactor
