Repository FRONTENDBOOTCAMP-13th/next-to-euid, pull requests merged in 2025-04, with the labels that each got.

#70 refactor♻️: Revising text,bg colors in page-main for increasing color contrast.
  src/styles/page-main.css
Labels: refactor

#71 refactor♻️: Improved color contrast in login button and input labels for better accessibility in dark and light modes.
  src/styles/login.css
  src/styles/signup.css
Labels: refactor

#73 refactor♻️: Modify page contrast errors
  src/styles/login.css
  src/styles/page-main.css
  src/styles/page-start-forgot-pw-email.css
  src/styles/page-start-forgot-pw-number.css
  src/styles/signup.css
  src/theme.css
Labels: enhancement, refactor

#74 fix 🐛: Fixed Prettier error
  .github/PULL_REQUEST_TEMPLATE.md
  .github/commit-rule.md
  README.md
  index.html
  package.json
  public/font/pretendardvariable.css
  src/component-board.html
  src/page-boardwith.html
  src/page-main.html
  src/pages/login-welcome.html
  src/signup.html
  src/styles/component-board.css
  src/styles/login.css
  src/styles/signup.css
  vite.config.js
Labels: bug, refactor
